version: '3.8'

services:
  portfolio:
    image: ghcr.io/hellcat46/portfolio:latest
    container_name: portfolio
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production