name: Production Deployment of Portfolio Site

on:
  push:
    branches:
      - main
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4 
        with:
          context: .
          push: true
          tags: ghcr.io/hellcat46/portfolio:latest  
          
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:       
      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ghcr.io/hellcat46/portfolio:latest
            
            docker stop portfolio || true
            docker rm portfolio || true
            
            docker run -d --name portfolio \
              -p 3000:3000 \
              -e NODE_ENV=production \
              --restart unless-stopped \
              ghcr.io/hellcat46/portfolio:latest